// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddAccount(arg1:models.Account):Promise<number>;

export function AddCategory(arg1:string):Promise<number>;

export function AddSubject(arg1:number,arg2:string):Promise<number>;

export function DeleteAccount(arg1:number):Promise<void>;

export function GeneratePost(arg1:number,arg2:number):Promise<number>;

export function GetAccounts():Promise<Array<models.Account>>;

export function GetCategories():Promise<Array<models.Category>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSubjects(arg1:number):Promise<Array<models.Subject>>;

export function Greet(arg1:string):Promise<string>;

export function PublishPost(arg1:number):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;
