// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AddSubject(arg1, arg2) {
  return window['go']['main']['App']['AddSubject'](arg1, arg2);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeletePost(arg1) {
  return window['go']['main']['App']['DeletePost'](arg1);
}

export function GeneratePost(arg1, arg2) {
  return window['go']['main']['App']['GeneratePost'](arg1, arg2);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetPost(arg1) {
  return window['go']['main']['App']['GetPost'](arg1);
}

export function GetPosts() {
  return window['go']['main']['App']['GetPosts']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetSubjects(arg1) {
  return window['go']['main']['App']['GetSubjects'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PublishPost(arg1) {
  return window['go']['main']['App']['PublishPost'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function UpdatePost(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePost'](arg1, arg2, arg3);
}
